=== ferdinand-dhbw/CICBO-back-end/schema/secret.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://CICBO.com/secrets.json",
  "type": "object",
  "title": "The root schema",
  "required": [
    "dbName",
    "collectionNameGuest",
    "collectionNameStaff",
    "collectionNameStaffShift",
    "collectionNameRoom",
    "collectionNameShiftRoom",
    "uri",
    "uriOptions",
    "protocol",
    "credentials"
  ],
  "properties": {
    "dbName": {
      "$id": "#/properties/dbName",
      "type": "string",
      "title": "The dbName schema"
    },
    "collectionNameGuest": {
      "$id": "#/properties/collectionNameGuest",
      "type": "string",
      "title": "The collectionNameGuest schema"
    },
    "collectionNameStaff": {
      "$id": "#/properties/collectionNameStaff",
      "type": "string",
      "title": "The collectionNameStaff schema"
    },
    "collectionNameStaffShift": {
      "$id": "#/properties/collectionNameStaffShift",
      "type": "string",
      "title": "The collectionNameStaffShift schema"
    },
    "collectionNameRoom": {
      "$id": "#/properties/collectionNameRoom",
      "type": "string",
      "title": "The collectionNameRoom schema"
    },
    "collectionNameShiftRoom": {
      "$id": "#/properties/collectionNameShiftRoom",
      "type": "string",
      "title": "The collectionNameShiftRoom schema"
    },
    "uri": {
      "$id": "#/properties/uri",
      "type": "string",
      "title": "The uri schema"
    },
    "uriOptions": {
      "$id": "#/properties/uriOptions",
      "type": "string",
      "title": "The uriOptions schema"
    },
    "protocol": {
      "$id": "#/properties/protocol",
      "type": "string",
      "title": "The protocol schema"
    },
    "credentials": {
      "$id": "#/properties/credentials",
      "type": "object",
      "title": "The credentials schema",
      "required": [
        "user",
        "pwd"
      ],
      "properties": {
        "user": {
          "$id": "#/properties/credentials/properties/user",
          "type": "string",
          "title": "The user schema"
        },
        "pwd": {
          "$id": "#/properties/credentials/properties/pwd",
          "type": "string",
          "title": "The pwd schema"
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== ferdinand-dhbw/CICBO-back-end/secrets/mongo-settings-with-credentials.prototype.json
{
  "dbName": "entries",
  "collectionNameGuest": "guest",
  "collectionNameStaff": "staff",
  "collectionNameStaffShift": "shift",
  "collectionNameRoom": "room",
  "collectionNameShiftRoom": "shift-room",
  "uri": "URL",
  "uriOptions": "retryWrites=true&w=majority",
  "protocol": "mongodb+srv",
  "credentials": {
    "user": "Username",
    "pwd": "Password"
  }
}
